= Gatling plugin for Gradle demo project

A simple showcase of a Gradle project using the
https://github.com/gatling/gatling-gradle-plugin/[Gatling plugin for Gradle]. The full documentation for the plugin can
be found https://gatling.io/docs/current/extensions/gradle_plugin/[on the Gatling website].

This project is written in Java, others are available for https://github.com/gatling/gatling-gradle-plugin-demo-kotlin[Kotlin]
and https://github.com/gatling/gatling-gradle-plugin-demo-scala[Scala].

It includes:

* minimal `build.gradle` leveraging Gradle wrapper
* latest version of `io.gatling.gradle plugin` applied
* sample
  https://javadoc.io/doc/io.gatling/gatling-core-java/latest/io/gatling/javaapi/core/Simulation.html[Simulation]
  class, demonstrating sufficient Gatling functionality
* proper source file layout

== Create sample project

For this quickstart: `git` must be installed and available in $PATH,
and a JDK must be installed and $JAVA_HOME configured.

[source, bash]
----
$ git clone https://github.com/gatling/gatling-gradle-plugin-demo-java.git
$ cd ./gatling-gradle-plugin-demo-java
----

== Run simulations

To test it out, use the following commands:

* Run all Gatling simulations at once

[source, bash]
----
$ ./gradlew gatlingRun
----

* Run a single simulation by its FQN (fully qualified class name)

[source, bash]
----
$ ./gradlew gatlingRun-computerdatabase.BasicSimulation
----

== Use with Gatling Enterprise Cloud

To package your simulation for https://gatling.io/enterprise/[Gatling Enterprise Cloud], run:

[source, bash]
----
$ ./gradlew gatlingEnterprisePackage
----

Check out https://gatling.io/docs/enterprise/cloud/reference/user/package_gen/#gradle-project[the documentation] for
more information, including how to upload the package to Gatling Enterprise Cloud directly from Gradle.

== Use with Gatling Enterprise Self-Hosted

This sample is ready for https://gatling.io/enterprise/[Gatling Enterprise Self-Hosted] to build from sources;
alternatively you can configure the build to publish to a binary repository. Check out
https://gatling.io/docs/enterprise/self-hosted/reference/current/user/binary/[the documentation] for more information.
