gatling.enterprise.package {
  name = "deployed package from gradle"
  team = "Default team"
  simulations = [
    {
      name = "mysimu deployed"
      # classname is mandatory if simulations is defined.
      classname = "computerdatabase.ComputerDatabaseSimulation"
      useDedicatedIps = false
      locations = [
        # name is mandatory if locations is defined.
        {
          #          name: "Local (Demo Purpose Only)",
          name: "Europe - Paris",
          size: 1,
          weight: 100
        }
      ]
      parameters {
        ignoreDefaults = false
        systemProperties {
          "com.example.prop" = "value frop system prop"
        }
        environmentVariables {
          MY_SIMULATION_ENV_VAR = "value from environment"
        }
      }
      timeWindow {
        rampUp = 0
        rampDown = 0
      }
    }
  ]
}
